name: Build Electron App
on:
  push:
    tags:
      - 'v*' # Starts building when you push a tag like v1.0.0

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build EXE
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: out/make/squirrel.windows/x64/*.exe
